language: objective-c
osx_image: xcode7
xcode_workspace: AffdexMe.xcworkspace
xcode_scheme: AffdexMe
xcode_sdk: iphonesimulator9.0
notifications:
    email: false

before_install:
  # Download and decompress the latest Affdex iOS SDK
  - pod install
  # Add mock license to the top of AffdexDemoViewController.m
  - echo '#define YOUR_AFFDEX_LICENSE_STRING_GOES_HERE @"{}"' | cat - apps/AffdexMe/Classes/AffdexDemoViewController.m > temp && mv temp apps/AffdexMe/Classes/AffdexDemoViewController.m
