source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/Affectiva/cocoapods-specs.git'
use_frameworks!

target 'AffdexMe' do
    pod 'AffdexSDK-iOS', '3.1-493'
    pod 'AWSKinesis'
end
