source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/Affectiva/cocoapods-specs.git'
use_frameworks!

target 'AffdexMe' do
    pod 'AffdexSDK-iOS', '3.1-493'
    pod 'AWSKinesis'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
      puts target.name
      if (target.name == "AWSCore") || (target.name == 'AWSKinesis')
          puts 'YABBA'
      end
      target.build_configurations.each do |config|
          config.build_settings['BITCODE_GENERATION_MODE'] = 'bitcode'
      end
  end
end
